# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    hostname = "hhvm.box"
    locale = "en_GB.UTF.8"

    # Box
    config.vm.box = "ubuntu/trusty64"

    # Shared folders
    config.vm.synced_folder ".", "/srv"

    # Setup
    config.vm.provision :shell, :inline => "touch .hushlogin"
    config.vm.provision :shell, :inline => "hostnamectl set-hostname #{hostname} && locale-gen #{locale}"
    config.vm.provision :shell, :inline => "apt-get update --fix-missing"
    config.vm.provision :shell, :inline => "apt-get install -q -y g++ make git curl vim"

    # All the keys and repos - hhvm
    config.vm.provision :shell, :inline => "apt-get install software-properties-common"
    config.vm.provision :shell, :inline => "apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449"
    config.vm.provision :shell, :inline => "sudo add-apt-repository \"deb http://dl.hhvm.com/ubuntu $(lsb_release -sc) main\""
    # nginx
    config.vm.provision :shell, :inline => "wget http://nginx.org/keys/nginx_signing.key"
    config.vm.provision :shell, :inline => "sudo apt-key add nginx_signing.key"
    config.vm.provision :shell, :inline => "rm nginx_signing.key"
    config.vm.provision :shell, :inline => "sudo add-apt-repository \"deb http://nginx.org/packages/ubuntu/ trusty nginx\""

    # Install hhvm and nginx
    config.vm.provision :shell, :inline => "sudo apt-get update"
    config.vm.provision :shell, :inline => "sudo apt-get -q -y install nginx hhvm"
    config.vm.provision :shell, :inline => "sudo update-rc.d hhvm defaults"
    config.vm.provision :shell, :inline => "sudo /usr/bin/update-alternatives --install /usr/bin/php php /usr/bin/hhvm 60"

    # Install mysql
    config.vm.provision :shell, :inline => "sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password password root'"
    config.vm.provision :shell, :inline => "sudo debconf-set-selections <<< 'mysql-server mysql-server/root_password_again password root'"
    config.vm.provision :shell, :inline => "sudo apt-get -y install mysql-server"

    # Install composer
    config.vm.provision :shell, :inline => "curl -s https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer"
    config.vm.provision :shell, :inline => "echo 'alias composer=\"hhvm -v ResourceLimit.SocketDefaultTimeout=30 -v Http.SlowQueryThreshold=30000 /usr/local/bin/composer\"' >> .bash_aliases"

    # Port forwarding
    default_ports = {
        80   => 8000,
        443  => 44300,
        3306 => 33060,
        5432 => 54320
    }

    default_ports.each do |guest, host|
        config.vm.network "forwarded_port", guest: guest, host: host
    end

end